version: '3.8'
services:
  db:
    image: mysql:9.0.1
    command:
    #  - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretrootpass
      MYSQL_DATABASE: abw
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    networks:
      - dbnet
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: api
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - '5000:5000'
    networks:
      - dbnet
    volumes:
      - uploads:/usr/local/app/uploads
networks:
  dbnet:
    driver: bridge
volumes:
  db_data:
  uploads:
